### PR TITLE
add script to scan files with correct mtime in storage but not in db

### PR DESCRIPTION
**Pull request by mgallien**
should allow to update mtime in db for files that are not handled by occ
groupfolders:scan <id>

Signed-off-by: Matthieu Gallien <matthieu.gallien@nextcloud.com>

### CODE REVIEW

**Comment by mgallien** [comment]
tested with postgresql
going to test now with mysql

**Comment by mgallien** [comment]
pushed a fix for mysql and everything is working

**Comment by artonge** [comment]
I don't understand which kind of file this will handle?
Call at 16:00?

**Comment by mgallien** [comment]
> I don't understand which kind of file this will handle? Call at 16:00?

OK for me

**Review by artonge — APPROVED** [review]

**Pull request merged**
